name: 'glamira_dbt'
version: '1.0.0'
profile: 'glamira_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  glamira_dbt:
    staging:
      +schema: staging
      +materialized: view
    core:
      +schema: core
      +materialized: table
    mart:
      +schema: mart
      +materialized: table

seeds:
  glamira_dbt:
    +schema: staging
    store_currency:
      +column_types:
        store_domain: string
        currency_code: string
        market_country_code: string
    exchange_rates:
      +column_types:
        currency_code: string
        usd_per_unit: numeric
